name: release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Generate OpenApi specification
        run: ./gradlew clean generateOpenApiDocs

      - name: Generate client from specification
        run: ./gradlew openApiGenerate

      - name: Build client
        run: cd build/generated/client; mvn clean install

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: release
        uses: actions/create-release@v1 # https://github.com/actions/create-release#example-workflow---create-a-release
        id: create_release
        with:
          draft: false
          prerelease: false
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload openApiSpecification artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/openapi.json
          asset_name: openApiSpecification_${{ steps.get_version.outputs.VERSION }}.json
          asset_content_type: application/json

      - name: upload generated client
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/generated/client/target/openapi-java-client-2.jar
          asset_name: generatedClient_${{ steps.get_version.outputs.VERSION }}.jar
          asset_content_type: application/java-archive

      # https://github.com/mr-smithers-excellent/docker-build-push
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: amartiushov/sut
          registry: docker.io
          tag: ${{ steps.get_version.outputs.VERSION }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

